language: emacs
cache: apt
env:
  - EVM_EMACS=emacs-25.1-travis
  - EVM_EMACS=emacs-25.2-travis
  - EVM_EMACS=emacs-25.3-travis
matrix:
  - fast_finish: true
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > travis.sh && source ./travis.sh
  - evm install $EVM_EMACS --use --skip
  # clj
  - curl -O https://download.clojure.org/install/linux-install.sh
  - chmod +x linux-install.sh
  - sudo ./linux-install.sh
install:
  - cask install
script:
  - export ECUKES_EMACS=${EMACS:-$(which emacs)}
  - $ECUKES_EMACS --version
  # Lint
  - cask emacs -batch -L . -l tests/lint.el
  # Test
  - echo "*** Starting Socket REPL on 5555 ***"
  - clojure -e "(do (require 'clojure.core.server) (clojure.core.server/start-server {:name :repl :port 5555 :accept 'clojure.core.server/repl :server-daemon false}))" &
  - until sudo fuser 5555/tcp; do sleep 0.1; done;
  - echo "*** Socket REPL Started ***"
  - cask exec buttercup -L . tests
  - kill $!
